import json


def main():
	"""
	This function is used to verify the bert sentence feat.
	The test_sent.json is generated by the original bert script, which contains the feature vector for each token.
	The test_sent_sentfeat.json is generated by the bert script after modification, which contains the feature vector
		for the whole sentence.
	This function calculate the sentence feature by averaging token features, and see if they are same
	:return:
	"""
	sentfeat = []
	with open("test_sent_sentfeat.json", 'r', encoding='utf8') as f:
		for line in f:
			content = json.loads(line.strip())
			sentfeat.append(content['features']['-1'])


	avg_sentfeat = []
	with open("test_sent.json", 'r', encoding='utf8') as f:
		for line in f:
			sum_featvec = None
			token_num = 0
			content = json.loads(line.strip())
			for token_info in content['features']:
				for layer in token_info['layers']:
					if layer['index'] == -1:
						current_vec = layer['values']
						if sum_featvec is None:
							sum_featvec = current_vec
						else:
							sum_featvec = [sum_featvec[i] + v for i, v in enumerate(current_vec)]
						token_num += 1
			sum_featvec = [x / token_num for x in sum_featvec]
			avg_sentfeat.append(sum_featvec)

	print(sentfeat[0][:10])
	print(avg_sentfeat[0][:10])

	for i in range(len(sentfeat[0])):
		if abs(sentfeat[0][i] - avg_sentfeat[0][i]) > 0.1:
			print("Different!")
			quit()
	print("Same!")

if __name__ == '__main__':
    main()
